### ISSUE TITLE
Error while installing packages with symbols in name

### ISSUE THREAD

**Issue by gmastergreatee** [camicri/camicri-cube#1]
For example after searching for __libc++1__, I click on download but an empty page comes up.

Thankyou for this app, very handy

**Comment by camicri** [comment]
Hello and thank you for sending report.

I have replicated the issue in my local machine and confirmed that it is a bug.
It seams that the '+' sign is being interpreted literally and not as a character.

For now, you can browse the following links in a separate browser tab to perform download and install.
Assuming that Cube app is running and the port you are using is 8080 (localhost:8080)

**Download libc++1**
`http://localhost:8080/cmd/download/download-package?package=libc%2B%2B1;`
Change all + character with %2B

**Install libc++1**
`http://localhost:8080/cmd/install/install-package?package=libc%2B%2B1;`

You should see the download progress in the terminal. 
Just check the `Asterisk => Downloaded` to confirm if the app is successfully downloaded.

Sorry for the inconvenience. I'll provide a fix as soon as possible.
