### ISSUE TITLE
symbol lookup error: /home/user/cube/cube-system/lib/libsoup-2.4.so.1: undefined symbol: g_cclosure_marshal_generic

### ISSUE THREAD

**Issue by schmedinghoff1** [camicri/camicri-cube#2]
I installed cube on an Ubuntu 10.04 system.
When I ran the "cube --terminal" command to the terminal window the above error appeared.
Any assistance would be appreciated
Thank you
Steve

**Comment by camicri** [comment]
Hello and thank you for sending your problem.

It seems that you are using a very old Ubuntu distribution. Cube is only tested on Ubuntu 14.04 and  up.

Also, I think repositories for Ubuntu 10.04 were no longer supported so you will not be able to install new apps to it. Consider upgrading to a newer and supported Ubuntu version.

**Comment by schmedinghoff1** [comment]
Hi Jake,
Thank you, I appreciate your quick answer.
You'd think I'd do just as you say.
  Well, that's not easily done as the offline computers that I'm talking
about *don't support PAE.*
*Nor does the next generation replacement '86DX3 processor'*
I'm certain you know that the last NONPAE ubuntu support is 10.04.
But what they do is what is now called IOT, and are very important for
health and safety.
Anyway, that's why I was attempting this.
Thanks again
Steve


On Tue, Feb 27, 2018 at 6:44 PM, Jake Capangpangan <notifications@github.com
