### ISSUE TITLE
64 bit to 32 bit

### ISSUE THREAD

**Issue by FrankPoule** [camicri/camicri-cube#3]
I've tried to create a project in my 32 bit offline computer, then open on my 64 bit and there's 2 problem : 1. I can't run the 32 bit cube
2. When I open the 32 bit project in the 64 bit cube, there's no packages or repository.

Thanks in advance!
Poule

**Comment by camicri** [comment]
Hello and sorry for my late response.

Could you give us more information like the OS and the version you are using?

Also, could you give us the content of the below file? This contains the repository list:
/projects/<your project name>/data/sources/sources.list

**Comment by camicri** [comment]
32 bit architecture is no longer supported.
