### ISSUE TITLE
fusermount: mount failed: Operation not permitted

### ISSUE THREAD

**Issue by Gabriel-p** [camicri/camicri-cube#4]
Trying to un this app in elementary OS Loki 64 bit I get:

    $ ./cube --terminal
    fusermount: mount failed: Operation not permitted
    open dir error: : No such file or directory

**Comment by camicri** [comment]
Hi, I know this is a bit late reply (6 months to be exact haha) but I didn't had a chance to test it on Elementary OS. I've been on idle since the first release and will try to review all the issues again.
